# Generated by Django 3.0.4 on 2021-08-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinchingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'w1'), (2, 'w2'), (3, 's1'), (4, 's2'), (5, 's3'), (6, 's4'), (7, 's5'), (8, '8'), (9, 'c1'), (10, 'c2'), (11, 'c3'), (12, 'pc1'), (13, 'pc2'), (14, 'rm1'), (15, 'rm2'), (16, 'urm')], null=True, verbose_name='Building Type')),
                ('pinch_x', models.FloatField(blank=True, null=True, verbose_name='Pinch X')),
                ('pinch_y', models.FloatField(blank=True, null=True, verbose_name='Pinch Y')),
                ('betta', models.FloatField(blank=True, null=True, verbose_name='Betta')),
                ('damp', models.FloatField(blank=True, null=True, verbose_name='Damping')),
            ],
            options={
                'verbose_name': 'Pinching Data',
                'verbose_name_plural': 'Pinching Data',
            },
        ),
    ]
