# Generated by Django 3.0.4 on 2021-08-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaddb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinchingdata',
            name='building_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'w1'), (2, 'w2'), (3, 's1'), (4, 's2'), (5, 's3'), (6, 's4'), (7, 's5'), (8, 'c1'), (9, 'c2'), (10, 'c3'), (11, 'pc1'), (12, 'pc2'), (13, 'rm1'), (14, 'rm2'), (15, 'urm')], null=True, verbose_name='Building Type'),
        ),
    ]
